### ISSUE TITLE
About encryption.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#10]
1. Is the encryption decryption done on the http body part only?
2. If 1 is not right, is the protocol format customizable?

Other questions:
3. Should "http://localhost/client1/test" behaves the same as "https://localhost/client1/test/" or not? The previous one can be a file. i.e. /data/client1/test is a directory, should the server return a 404 when accessing to "http://localhost/client1/test" or not?
4. Is the API that allows HEAD not appearing in the documentation?
5. Do breakpoint transmission need to support `chunked=1` (transfer-encoding: chunked)?
6. About session expiration: When user use `session-id=xxx` to request, should server reset the cookie's expire time? i.e. Is the cookie fixed for a user to use only for a certain period of time after a single login, during which time the password needs to be re-entered when it expires (and a new cookie will be set), regardless of whether it is accessed consecutively or not?
7. If the uploaded file's name is same to an existed file, should server rename it or overwrite it?
8. Is a user allowed to delete its own root directory?

Thank you.

**Comment by Mark4551124015** [comment]
1. Whatever you want. It will check by TAs in you lab. Bonus part is customized. You can design your own encrytion method or simply folled by HTTPS in RFC.
2. Whatever. (But encryption should not be too weak like `base64`)
3. As long as you can access server fluently by a browser, its doesn't matter. Robust is not consider as critical point in Bonus Part.
4. Yes, we won't check them.
5. No, this two functions should not be triggered together. They are not consistent in RFC.
6. No, it won't resumed. But accepted requests should not be shutdown (like long term downloading).
7. Overwrite, but we wont test this in robust test.
8. Doesn't matter. Since this directory will be create automatically when using `HTTP Post` is upload it's file.

**Comment by Gralerfics** [comment]
Thank you!
