### ISSUE TITLE
Question about the test demo on blackboard

### ISSUE THREAD

**Issue by QinYuzhou** [Leosang-lx/SUSTech-CS305-2023Fall#40]
When I access the url `http://localhost:8080/`.
My server will respond `400 Bad Request`, because it thinks that this url missed the query parameter `SUSTech-HTTP`.
But the test demo on blackboard will respond `200 OK`
<img width="460" alt="截屏2023-12-14 20 36 19" src="https://github.com/Leosang-lx/SUSTech-CS305-2023Fall/assets/90183764/a1eda0a6-1fd6-4cc5-a7ea-06a40e95d56f">

**Comment by Leosang-lx** [comment]
Maybe the document is a little bit confusing, and the document has been updated with `SUSTech-HTTP` being set as an **optional** query parameter (instead of **required** parameter because of my wrong understanding).
Therefore, the URL without query parameter `SUSTech-HTTP` is valid which means `SUSTech-HTTP=0` in default.
