### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by Gralerfics** [Leosang-lx/SUSTech-CS305-2023Fall#7]
1. When will the latest test document be released approximately?
2. What are the `SUSTech-HTTP` parameters that appear in the test demo on blackboard?
3. About set-cookie. e.g., when accessing (e.g. uploading file into) `/user1/abc`, the user provides the correct password for `user2`, should the server return `403 Forbidden` along with the `set-cookie`, so that the user doesn't have to log in again after switching to another directory?
4. Can a client view others' directory?
5. About `chunked=1`, is the chunk size customizable?
6. About `chunked=1`, is it possible that this parameter is attached when the user GET a directory instead of a file?
7. About whitelist, is it only install whitelisted modules in the test environment? If not will custom packages be affected?
8. Is the status description text customizable, e.g. Bad Request followed by a specific error?
9. Is the path in URL case-sensitive?
10. Can directories be deleted?
11. In upload and delete part of the document, should there be a 400 Bad Request when the parameter `path` is missing or invalid?
12. The certain expire time for a session-id?
13. Is there any limitations to the upload file operations during testing? (e.g. fixing the upload as multipart/form-data, etc.)

Thank you.

**Comment by Leosang-lx** [comment]
Patial:
1.
2.
3. In this case, return `403 Forbidden` since you want to modify user1 with authorization of user2, and return set-cookie including the session-id of user2 since you log in with user2.
4. A client can view and download any files listed under `/data/` in server
5. You can customize the chunk size
6. We don't consider this case
7. 
8. 
9. Y
10. Y
11. Yes, and this reminds me that uploading and deleting with cases of 400 bad request should be added to the project description
12. You can firstly set a short session-id when testing your code, and this will be given in testing, probably 10s
13.

**Comment by Mark4551124015** [comment]
2. It's an URL arg, file-list requests with `SUSTech-HTTP=1` would require you to return a brief view of file list (will be explained in test document). We will check you frontend in lab, but functional evaluation will be done by scripts. 
7. We will test on your enviroment, and you'd better not use them in you code. Or it will cause **REALLY BAD CONSQUENCES**. Installation is fine as long as you don't use them. You need to provide a `requirements.txt` which will only cover the whitelisted modules after we check in lab. Utilization of modules will be checked by scripts.  Your code should be nice  while only install `requirements.txt`.
8. Do what ever you want in that text, e.g. `404 Geeeeez why you do this` 
13. It's kind of fixed in `multipart/form-data`, since we will use `requests` module to generate HTTP POST request.

**Comment by Mark4551124015** [comment]
You can close this if all your questions is specified. Thank you!

**Comment by Gralerfics** [comment]
Thank you!
